Sprint 09
zksystem/imageFeed pull request #2
Opened 2023-01-30 20:58 UTC by zksystem

2023-01-31 19:31 UTC, IBDesignable requested changes

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
Можно сделать приватным

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private let ShowSingleImageSegueIdentifier = "ShowSingleImage"
Настаиваю на нижнем camelCase, так как это не тип, а свойство

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let indexPath = sender as! IndexPath
Не смотря на то, что здесь в целом не будет ошибки, все-таки код будет выглядеть сильнее, если делать честное разворачивание всех опционалов.

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    }()
Давай перенесем рядом к свойствам

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/ImagesList/imagesListViewController.swift
> +            let indexPath = sender as! IndexPath
аналогичный комментарий

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/ImagesList/imagesListViewController.swift
> +            let indexPath = sender as! IndexPath
так, стоп, а почему у тебя два класса одинаковых? давай лишний дропнем

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        self.imageViewUserPic = imageViewUserPic
обычно отделяют настройку вьюх от констрейнтов. 

например так

```swift
private lazy var view: UIView = {
let view = UIView() 
view.backgroundColor = .red
/// другая настройка свойств
return view
}
```

затем делают один метод setupLayout. 

И там описывают все ограничения. 

Также, советую использовать групповую активацию как можно чаще/приоритетнее, так как она делает это за одну транзацкию,  в отличие от формата .isActive = true

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        labelFullName.font = UIFont.boldSystemFont(ofSize: 23.0)
пропущен weight

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        labelGreetings.font = UIFont.systemFont(ofSize: 18.0)
большеват, в дизайне меньше

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        let button = UIButton.systemButton(
комментарий верно написан, а переменная – не понятно что за кнопка, кому нужна )

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        button.centerYAnchor.constraint(equalTo: imageViewUserPic.centerYAnchor).isActive = true
это хорошо сделано

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +        let image = imageView.image
модификаторы доступа пропущены

2023-01-31 19:31 UTC, IBDesignable commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +        let imageToShare = [ image! ]
лучше разыменовать, чем форсанврапить

2023-02-01 18:01 UTC, zksystem commented on ImageFeed/ImagesList/imagesListViewController.swift
> +            let indexPath = sender as! IndexPath
класс один, переименовывал, дифф так показал почему-то

2023-02-01 18:26 UTC, zksystem commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let indexPath = sender as! IndexPath
fixed

2023-02-01 18:26 UTC, zksystem commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private let ShowSingleImageSegueIdentifier = "ShowSingleImage"
done

2023-02-01 18:27 UTC, zksystem commented on ImageFeed/Profile/ProfileViewController.swift
> +        let button = UIButton.systemButton(
renamed

2023-02-01 18:48 UTC, zksystem commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +        let image = imageView.image
fixed

2023-02-01 18:48 UTC, zksystem commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +        let imageToShare = [ image! ]
done

2023-02-02 18:41 UTC, IBDesignable commented
Я в прошлый раз вроде писала, что у таба профиля иконка не проставлена. 

Возможно у тебя отображается ок, а вот в гит с проблемой закомитилось: то что упомянуто в сториборде не соответствует тому, что сохранено в ассатах
<img width="240" alt="Снимок экрана 2023-02-02 в 20 34 32" src="https://user-images.githubusercontent.com/121577115/216419685-a0282d94-b381-4836-b262-04404346df95.png">

2023-02-02 18:44 UTC, IBDesignable commented
Не сильно критично, но будет супер, если доправишь в пиксель-перфект отступы и размеры. 
Сейчас сильно бросается в глаза что имя девушки  отрисовано не в bold начертании, и иконка сплющена:
<img width="371" alt="Снимок экрана 2023-02-02 в 20 42 32" src="https://user-images.githubusercontent.com/121577115/216420103-f2804d98-693f-4531-bd0a-03ca124cd7d7.png">
<img width="376" alt="Снимок экрана 2023-02-02 в 20 42 21" src="https://user-images.githubusercontent.com/121577115/216420110-67348051-4683-4715-ad8c-3c4f32a65017.png">

Ну и обрати внимание, что по макетам статус бар всегда белый

2023-02-05 09:18 UTC, zksystem commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
done

2023-02-05 09:39 UTC, merged